version: '2.2'

services: 
    nginx:
        build: ./nginx
        ports:
            - 80:80
            - 443:443
        command: nginx -g 'daemon off;'
        volumes: 
            - ./nginx:/var/www/localhost/html
    wordpress:
        build: ./wordpress
        command: php-fpm7.3 -F -R

